export const items = [
  {
    id: 1,
    firstName: "Joya",
    lastName: "Nardis",
    slug: "VnCmYLyNw",
    biography:
      "BdsZtiBRVmSjAhlEwnLtIAzPddkgFzCDVjksOOfnFgdTTuWmDvzUjyTpgMjhvzlxDqAFlwSxPgncUmdFAlNB",
    createdAt: "2023-02-28T17:32:44.834Z",
    isDeleted: true,
    imagesIDs: [817],
  },
  {
    id: 2,
    firstName: "Rene",
    lastName: "Belfiore",
    slug: "IisfNkAQABU",
    biography:
      "PPZJmgpuZBSVRaCldHpDxABARuYsQkmcwmVOkHftGTnYdCteWHTpuMxfYXoNHJZbWRseBSGFagTyNmGcvHplfnsmiDpg",
    createdAt: "2021-07-15T09:19:03.897Z",
    isDeleted: true,
    imagesIDs: [69],
  },
  {
    id: 3,
    firstName: "Ralph",
    lastName: "Mcgee",
    slug: "dDSKVWFGfWxrO",
    biography:
      "dFSbnJsvElYLGDiEqSvTCgSTUPTEuSyqDEmYdPrTqsFNKwMDSqrNmsmSNirwAcNaXfoARbTRZtRvIdXkcOBiPxGoI",
    createdAt: "2022-03-04T20:31:08.794Z",
    isDeleted: true,
    imagesIDs: [357],
  },
  {
    id: 4,
    firstName: "Gabriel",
    lastName: "Jimenez",
    slug: "IBqYInMIMn",
    biography:
      "INPlVxVWcNhbsdsytFHYDqlUBeMJoHMCXaMctqFxnAJzzNUgFCcmICIdybCjtzzMnoToqLLwKTQOwrq",
    createdAt: "2021-04-12T07:50:43.728Z",
    isDeleted: false,
    imagesIDs: [254],
  },
  {
    id: 5,
    firstName: "Leila",
    lastName: "Valenti",
    slug: "qdxlPNWjsDWQ",
    biography:
      "kTVoMcCHcewYkwJUCuyNBjruRuOhzxfRFsiFCsbyovNHeNKfoeDAgyXrkSfqDdnipkVJtxjMbuUzOlthdPNTscudQH",
    createdAt: "2023-07-22T16:10:23.226Z",
    isDeleted: false,
    imagesIDs: [43],
  },
  {
    id: 6,
    firstName: "Coleman",
    lastName: "Tripp",
    slug: "gKzmHPWepblxno",
    biography: "pJmDFmmPBClxyVZtxzwyVEkxKsAfkpHLQbRkNTyBcxfZseNdpFZTZauBxM",
    createdAt: "2023-02-08T05:41:16.822Z",
    isDeleted: false,
    imagesIDs: [125],
  },
  {
    id: 7,
    firstName: "Dawn",
    lastName: "Whitmore",
    slug: "qTvJfgrsvikHS",
    biography:
      "VSLJQuTTkOmxLqXHCKAhEZKHTzVVjFifjPqWmbmBxzzLHpTphfuajqobXZbyqnyZbrVRHp",
    createdAt: "2021-06-13T14:11:47.422Z",
    isDeleted: false,
    imagesIDs: [571],
  },
  {
    id: 8,
    firstName: "Alison",
    lastName: "Hawkins",
    slug: "hvoMcGujMcLFe",
    biography:
      "GgAplHsBCpmyNXGiEVBuvEzQqWxSRpNKNdrEcWXOTYnducNppgfQiSDRijmeNUHKgNyNMbXubptpSkntTKVFbRDSOHcz",
    createdAt: "2020-06-28T00:33:48.092Z",
    isDeleted: false,
    imagesIDs: [318],
  },
  {
    id: 9,
    firstName: "Susanna",
    lastName: "Cassidy",
    slug: "CCHVSoSnuWZ",
    biography:
      "gOgnoWxrkJztGXQCLTcqXBQFWVRPLdKsMAlxUvkrpWJRMUquxGcAbMWAkZXbmwqABGAhcaOvNRGACWYeTAaNzoOCNH",
    createdAt: "2023-05-17T10:32:50.469Z",
    isDeleted: true,
    imagesIDs: [128],
  },
  {
    id: 10,
    firstName: "Theresa",
    lastName: "Nichols",
    slug: "WXXPNHHRRBH",
    biography:
      "PeWqUxnnyguEHKwbPKkHytvBLeDFVUbEKNGmfFvFsNKJVrJwTbQvqROQMPFDLhtivgKpVKgfVJpivONF",
    createdAt: "2021-04-11T11:20:31.893Z",
    isDeleted: true,
    imagesIDs: [765],
  },
  {
    id: 11,
    firstName: "Madeline",
    lastName: "Anthony",
    slug: "ckFtFqVxzoIf",
    biography:
      "FGcDdlSYMMVjUtOHILyRXunBdHriCEVwjLxARxPGHZMbBVptFXUYoXnqUWLXcYmryyHbbnzevCbQSlVNlBRrhwgpd",
    createdAt: "2023-01-11T13:34:27.993Z",
    isDeleted: false,
    imagesIDs: [492],
  },
  {
    id: 12,
    firstName: "Trenton",
    lastName: "Lawson",
    slug: "ehnQMTnqqfC",
    biography:
      "fOnCskRXUKHeZypUnbKHVSNCnVDjSwcttznOgnrAwhgtMBDWSEgSgOvRUQPLAHciKMFFAUfBDPUbnFYP",
    createdAt: "2022-05-07T04:01:13.507Z",
    isDeleted: true,
    imagesIDs: [58],
  },
  {
    id: 13,
    firstName: "Tracy",
    lastName: "Bowling",
    slug: "PYpQvsXibKcctP",
    biography:
      "sntzCwfCUgWAGMfXKXBRlXmSHuAxvcTizvGxuYPGrseGZoKvOSBDPrIRuRoigQBMOGvmmXrelihzfzqMJ",
    createdAt: "2023-01-12T01:21:13.596Z",
    isDeleted: false,
    imagesIDs: [991],
  },
  {
    id: 14,
    firstName: "Maritza",
    lastName: "Long",
    slug: "GjuxetEGHvCJ",
    biography:
      "zNjbMCIGegjIZvZjJBOJWoDSaQtqsDpdmHxPNLhtlTxOmEqSrHHFojAakgEFOPJviTFlZPVbJjjbMKnBMdGnKa",
    createdAt: "2023-02-26T05:47:07.820Z",
    isDeleted: false,
    imagesIDs: [962],
  },
  {
    id: 15,
    firstName: "Kari",
    lastName: "Gentry",
    slug: "dHZGIzMHnoz",
    biography: "VoTYZkrCtCWhnZmgfGkRcdyMtHdyQysUpisxSR",
  },
];
